services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    container_name: chatapp-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - db
    env_file: .env

  frontend:
    container_name: chatapp-frontend
    env_file: .env
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: prod
      args:
        - VITE_API_BASE_URL_PROD=$API_BASE_URL_PROD
        - VITE_API_BASE_URL_LOCAL=$API_BASE_URL_LOCAL
    stdin_open: true
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"


volumes:
  postgres_data:
    name: chatapp_postgres_data